name: Testes BDD com Behave

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  behave-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # ou qualquer versão compatível com seu projeto

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar testes BDD
        run: behave
